'use server'

import { auth } from '@/auth'
import { prisma } from '@/lib/prisma'
import { log } from '@/lib/logger'
import { revalidatePath } from 'next/cache'
import { normalizeTranslationRecord } from '@/types/cms'

const allowedRoles = ['ADMIN', 'SUPERADMIN', 'SUPER_ADMIN']

async function ensureAdmin() {
  const session = await auth()
  const role = typeof session?.user?.role === 'string' ? session.user.role : 'GUEST'
  if (!session || !allowedRoles.includes(role)) {
    throw new Error('Forbidden')
  }
  return { session, role }
}

export async function updateSiteConfigAction(key: string, value: string, locale: string) {
  const { role } = await ensureAdmin()

  try {
    const current = await prisma.siteConfig.findUnique({ where: { key } })
    const currentValues = (current?.publishedValues as Record<string, string>) || {}
    const newValues = { ...currentValues, [locale]: value }

    await prisma.siteConfig.upsert({
      where: { key },
      create: {
        key,
        label: key,
        type: 'text',
        group: 'autogenerated',
        publishedValues: newValues,
        draftValues: newValues
      },
      update: {
        publishedValues: newValues,
        draftValues: newValues
      }
    })

    await log('info', 'CMS Direct Edit: SiteConfig', { key, locale, role })
    revalidatePath('/', 'layout')
    return { success: true }
  } catch (e) {
    console.error(e)
    return { success: false, error: String(e) }
  }
}

export async function updateHeroSlideAction(
  id: string,
  field: 'title' | 'subtitle' | 'imageDesktop' | 'imageMobile',
  value: string,
  locale: string
) {
  const { role } = await ensureAdmin()

  try {
    const slide = await prisma.heroSlide.findUnique({ where: { id } })
    if (!slide) throw new Error('Slide not found')

    const updateData: Record<string, any> = {}

    if (field === 'title' || field === 'subtitle') {
      const currentRecord = (slide[field] as Record<string, string>) || {}
      const newRecord = { ...currentRecord, [locale]: value }
      updateData[field] = normalizeTranslationRecord(newRecord)
    } else {
      // For images (simple strings), we just update the value directly
      // Image fields are not localized in this schema, so we ignore locale
      updateData[field] = value
    }

    // Update draftPayload safely
    const currentDraft = (slide.draftPayload as Record<string, any>) || {}
    const newDraft = { ...currentDraft, ...updateData }

    await prisma.heroSlide.update({
      where: { id },
      data: {
        ...updateData,
        draftPayload: newDraft
      }
    })

    await log('info', 'CMS Direct Edit: HeroSlide', { id, field, locale, role })
    revalidatePath('/', 'layout')
    return { success: true }
  } catch (e) {
    console.error(e)
    return { success: false, error: String(e) }
  }
}
