'use server'

import { auth } from '@/auth'
import { prisma } from '@/lib/prisma'
import { log } from '@/lib/logger'
import { revalidatePath } from 'next/cache'
import { normalizeTranslationRecord } from '@/types/cms'

const allowedRoles = ['ADMIN', 'SUPERADMIN', 'SUPER_ADMIN']

async function ensureAdmin() {
  const session = await auth()
  const role = typeof session?.user?.role === 'string' ? session.user.role : 'GUEST'
  if (!session || !allowedRoles.includes(role)) {
    throw new Error('Forbidden')
  }
  return { session, role }
}

export async function updateSiteConfigAction(key: string, value: string, locale: string) {
  const { role } = await ensureAdmin()

  try {
    // 1. Fetch current config
    const current = await prisma.siteConfig.findUnique({ where: { key } })

    // 2. Prepare update
    // If it exists, we merge the translation. If not, we create.
    const currentValues = (current?.publishedValues as Record<string, string>) || {}
    const newValues = { ...currentValues, [locale]: value }

    // We also update draftValues for consistency, though this "Direct Edit" mode bypasses draft flow
    await prisma.siteConfig.upsert({
      where: { key },
      create: {
        key,
        label: key, // Fallback label
        type: 'text',
        group: 'autogenerated',
        publishedValues: newValues,
        draftValues: newValues
      },
      update: {
        publishedValues: newValues,
        draftValues: newValues
      }
    })

    await log('info', 'CMS Direct Edit: SiteConfig', { key, locale, role })
    revalidatePath('/', 'layout') // Revalidate everything
    return { success: true }
  } catch (e) {
    console.error(e)
    return { success: false, error: String(e) }
  }
}

export async function updateHeroSlideAction(id: string, field: 'title'|'subtitle', value: string, locale: string) {
  const { role } = await ensureAdmin()

  try {
    const slide = await prisma.heroSlide.findUnique({ where: { id } })
    if (!slide) throw new Error('Slide not found')

    const currentRecord = (slide[field] as Record<string, string>) || {}
    const newRecord = { ...currentRecord, [locale]: value }
    const normalized = normalizeTranslationRecord(newRecord)

    await prisma.heroSlide.update({
      where: { id },
      data: {
        [field]: normalized,
        // Also update draft payload to keep in sync
        draftPayload: {
             ...(slide.draftPayload as object),
             [field]: normalized
        }
      }
    })

    await log('info', 'CMS Direct Edit: HeroSlide', { id, field, locale, role })
    revalidatePath('/', 'layout')
    return { success: true }
  } catch (e) {
    console.error(e)
    return { success: false, error: String(e) }
  }
}
