#!/bin/bash
# Blue-Green Deployment Switch Script
# Usage: ./blue-green-switch.sh [blue|green] [--rollback]
#
# This script performs zero-downtime deployments by:
# 1. Starting the new color instance
# 2. Waiting for health check
# 3. Switching nginx upstream
# 4. Gracefully stopping the old instance

set -e

# Configuration
COMPOSE_FILE="docker-compose.yml"
BLUEGREEN_FILE="docker-compose.bluegreen.yml"
NGINX_UPSTREAM_CONF="/etc/nginx/conf.d/bluegreen-upstream.conf"
STATE_FILE="/var/lib/sweet-narcisse/deployment-state.json"
HEALTH_CHECK_RETRIES=30
HEALTH_CHECK_INTERVAL=2

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get current active color from state file
get_active_color() {
    if [ -f "$STATE_FILE" ]; then
        jq -r '.active // "blue"' "$STATE_FILE"
    else
        echo "blue"
    fi
}

# Get opposite color
get_opposite_color() {
    local current=$1
    if [ "$current" == "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

# Save deployment state
save_state() {
    local active=$1
    local blue_status=$2
    local green_status=$3
    local timestamp=$(date -Iseconds)
    
    mkdir -p "$(dirname "$STATE_FILE")"
    cat > "$STATE_FILE" << EOF
{
    "active": "$active",
    "blue": "$blue_status",
    "green": "$green_status",
    "lastSwitch": "$timestamp",
    "version": "${DOCKER_IMAGE_TAG:-latest}"
}
EOF
    log_info "State saved: active=$active"
}

# Health check function
health_check() {
    local color=$1
    local port=$2
    local url="http://localhost:$port/api/health"
    
    for i in $(seq 1 $HEALTH_CHECK_RETRIES); do
        log_info "Health check attempt $i/$HEALTH_CHECK_RETRIES for $color..."
        
        response=$(curl -s -o /dev/null -w "%{http_code}" "$url" 2>/dev/null || echo "000")
        
        if [ "$response" == "200" ]; then
            log_success "$color instance is healthy"
            return 0
        fi
        
        sleep $HEALTH_CHECK_INTERVAL
    done
    
    log_error "$color instance failed health check after $HEALTH_CHECK_RETRIES attempts"
    return 1
}

# Start container for specific color
start_instance() {
    local color=$1
    log_info "Starting $color instance..."
    
    docker compose -f "$COMPOSE_FILE" -f "$BLUEGREEN_FILE" up -d "app-$color"
    
    local port
    if [ "$color" == "blue" ]; then
        port=3001
    else
        port=3002
    fi
    
    if health_check "$color" "$port"; then
        log_success "$color instance started and healthy"
        return 0
    else
        log_error "Failed to start $color instance"
        return 1
    fi
}

# Stop container for specific color
stop_instance() {
    local color=$1
    log_info "Stopping $color instance..."
    
    docker compose -f "$COMPOSE_FILE" -f "$BLUEGREEN_FILE" stop "app-$color"
    docker compose -f "$COMPOSE_FILE" -f "$BLUEGREEN_FILE" rm -f "app-$color"
    
    log_success "$color instance stopped"
}

# Switch nginx upstream
switch_upstream() {
    local new_active=$1
    local port
    
    if [ "$new_active" == "blue" ]; then
        port=3001
    else
        port=3002
    fi
    
    log_info "Switching nginx upstream to $new_active..."
    
    # Update nginx upstream configuration
    cat > "$NGINX_UPSTREAM_CONF" << EOF
# Blue-Green Nginx Upstream Configuration
# Auto-generated by blue-green-switch.sh
# Active: $new_active - $(date)

upstream sweet_narcisse_blue {
    server app-blue:3001 max_fails=3 fail_timeout=30s;
    keepalive 32;
}

upstream sweet_narcisse_green {
    server app-green:3002 max_fails=3 fail_timeout=30s;
    keepalive 32;
}

upstream sweet_narcisse_active {
    server app-${new_active}:${port};
    keepalive 32;
}

server {
    listen 8080;
    server_name _;
    
    location /health/blue {
        proxy_pass http://sweet_narcisse_blue/api/health;
        proxy_connect_timeout 5s;
        proxy_read_timeout 5s;
    }
    
    location /health/green {
        proxy_pass http://sweet_narcisse_green/api/health;
        proxy_connect_timeout 5s;
        proxy_read_timeout 5s;
    }
    
    location /health/active {
        proxy_pass http://sweet_narcisse_active/api/health;
        proxy_connect_timeout 5s;
        proxy_read_timeout 5s;
    }
    
    location /deployment/status {
        default_type application/json;
        return 200 '{"active": "${new_active}", "timestamp": "$(date -Iseconds)"}';
    }
}
EOF

    # Test nginx configuration
    if nginx -t 2>/dev/null; then
        nginx -s reload
        log_success "Nginx reloaded with $new_active upstream"
    else
        log_error "Nginx configuration test failed!"
        return 1
    fi
}

# Main deployment function
deploy() {
    local target_color=$1
    local current_active=$(get_active_color)
    
    if [ -z "$target_color" ]; then
        target_color=$(get_opposite_color "$current_active")
    fi
    
    log_info "=========================================="
    log_info "Blue-Green Deployment"
    log_info "Current active: $current_active"
    log_info "Target: $target_color"
    log_info "=========================================="
    
    # Pull latest image if specified
    if [ -n "$DOCKER_IMAGE_TAG" ]; then
        log_info "Pulling image with tag: $DOCKER_IMAGE_TAG"
        docker pull "ghcr.io/kalicat/sweet-narcisse:$DOCKER_IMAGE_TAG"
    fi
    
    # Start new instance
    if ! start_instance "$target_color"; then
        log_error "Deployment failed: could not start $target_color instance"
        exit 1
    fi
    
    # Switch traffic
    if ! switch_upstream "$target_color"; then
        log_error "Deployment failed: could not switch upstream"
        # Rollback: stop the new instance
        stop_instance "$target_color"
        exit 1
    fi
    
    # Wait for traffic to drain (optional grace period)
    log_info "Waiting 10s for traffic to drain from $current_active..."
    sleep 10
    
    # Stop old instance
    if [ "$current_active" != "$target_color" ]; then
        stop_instance "$current_active"
    fi
    
    # Save state
    save_state "$target_color" \
        "$([ "$target_color" == "blue" ] && echo "running" || echo "stopped")" \
        "$([ "$target_color" == "green" ] && echo "running" || echo "stopped")"
    
    log_success "=========================================="
    log_success "Deployment complete!"
    log_success "Active: $target_color"
    log_success "=========================================="
}

# Rollback to previous color
rollback() {
    local current_active=$(get_active_color)
    local rollback_target=$(get_opposite_color "$current_active")
    
    log_warn "=========================================="
    log_warn "ROLLBACK initiated"
    log_warn "Current: $current_active"
    log_warn "Rolling back to: $rollback_target"
    log_warn "=========================================="
    
    # Start the old instance (it should still have the previous version)
    if ! start_instance "$rollback_target"; then
        log_error "Rollback failed: could not start $rollback_target instance"
        exit 1
    fi
    
    # Switch traffic
    switch_upstream "$rollback_target"
    
    # Stop current (broken) instance
    stop_instance "$current_active"
    
    # Save state
    save_state "$rollback_target" \
        "$([ "$rollback_target" == "blue" ] && echo "running" || echo "stopped")" \
        "$([ "$rollback_target" == "green" ] && echo "running" || echo "stopped")"
    
    log_success "Rollback complete! Active: $rollback_target"
}

# Status function
status() {
    echo "=========================================="
    echo "Blue-Green Deployment Status"
    echo "=========================================="
    
    if [ -f "$STATE_FILE" ]; then
        cat "$STATE_FILE" | jq .
    else
        echo "No state file found. Run a deployment first."
    fi
    
    echo ""
    echo "Container Status:"
    docker ps --filter "name=sweet-narcisse-blue" --filter "name=sweet-narcisse-green" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
}

# Parse arguments
case "${1:-deploy}" in
    blue)
        deploy "blue"
        ;;
    green)
        deploy "green"
        ;;
    deploy)
        deploy ""
        ;;
    rollback|--rollback)
        rollback
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 [blue|green|deploy|rollback|status]"
        echo ""
        echo "Commands:"
        echo "  blue      Deploy to blue instance"
        echo "  green     Deploy to green instance"
        echo "  deploy    Deploy to opposite of current active"
        echo "  rollback  Rollback to previous instance"
        echo "  status    Show current deployment status"
        exit 1
        ;;
esac
